osx_image: xcode9.2
language: objective-c

cache:
  - bundler

before_script:
  - make ci

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor.bundle}

script:
  - make build
  - make lint
